root __INSTALL_DIR__/static;

location /media {
  root /home/yunohost.app/__APP__;
  expires 336h;
  try_files $uri @proxy_to_app;
}

location /static/ {
  alias __INSTALL_DIR__/staticfiles/;
}

location /logo {
  root /home/yunohost.app/__APP__;
  try_files $uri @proxy_to_app;
}

location / {
  try_files $uri @proxy_to_app;
}

location /api {
  location ~ @ {
      return 404;
  }

  location ~ /\.json$ {
      return 404;
  }
  try_files $uri @proxy_to_app;
}

location @proxy_to_app {
  proxy_pass        http://unix:/run/__APP__.sock;
  include           proxy_params_no_auth;
}

location ~ /(favicon.ico|favicon.png|robots.txt|clientconfig.json) {
  expires 336h; # 2 weeks
}
