#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICES
#=================================================
ynh_script_progression "Stopping $app's systemd services..."

ynh_systemctl --service="$app-celery" --action="stop"

ynh_systemctl --service="$app-beat" --action="stop"

ynh_systemctl --service="$app.socket" --action="stop"

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
ynh_script_progression "Updating $app's configuration files..."

mkdir -p "$env_path"
echo "$new_domain" > "$env_path/DEFAULT_BASE_URL"
echo "$app@$new_domain" > "$env_path/DEFAULT_FROM_EMAIL"
echo "$app@$new_domain" > "$env_path/SERVER_EMAIL"

set_permissions

#=================================================
# START SYSTEMD SERVICES
#=================================================
ynh_script_progression "Starting systemd services..."

ynh_systemctl --service="$app.socket" --action="start"

ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service="$app-celery" --action="start"

ynh_systemctl --service="$app-beat" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
