#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

# Remove the dedicated systemd config
systemctl stop "$app.socket" --quiet
systemctl disable "$app.socket" --quiet
rm "/etc/systemd/system/$app.socket"
systemctl daemon-reload --quiet

ynh_config_remove_systemd
ynh_config_remove_systemd -s "$app-celery"
ynh_config_remove_systemd -s "$app-beat"

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
