#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chmod -R o-rwx "$data_dir"
chown -R "$app:www-data" "$data_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chown -R "$app:www-data" "$data_dir"

# Restore permissions on app files
set_permissions

#=================================================
# RESTORE THE PSQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
ynh_restore "/etc/systemd/system/$app-celery.service"
ynh_restore "/etc/systemd/system/$app-beat.service"
ynh_restore "/etc/systemd/system/$app.socket"

systemctl enable "$app-celery" --quiet
systemctl enable "$app-beat" --quiet
systemctl enable "$app" --quiet
systemctl enable "$app.socket" --quiet
yunohost service add "$app" --description="Manage podcast subscriptions, and sync them between apps and devices" --log=systemd

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app.socket" --action="start" --log_path=systemd --wait_until="Listening on"
ynh_systemctl --service="$app" --action="start" --log_path=systemd
ynh_systemctl --service="$app-celery" --action="start" --log_path=systemd --wait_until="ready."
ynh_systemctl --service="$app-beat" --action="start" --log_path=systemd --wait_until="Starting..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
