#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression --message="Restoring the data directory..."

ynh_restore_file --origin_path="$data_dir" --not_mandatory

chmod -R o-rwx "$data_dir"
chown -R "$app:www-data" "$data_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression --message="Restoring the data directory..." --weight=1

ynh_restore_file --origin_path="$data_dir" --not_mandatory

chown -R "$app:www-data" "$data_dir"

# Restore permissions on app files
set_permissions

#=================================================
# RESTORE THE PSQL DATABASE
#=================================================
ynh_script_progression --message="Restoring the PostgreSQL database..." --weight=1

ynh_psql_connect_as --user="$db_user" --password="$db_pwd" --database="$db_name" < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
ynh_restore_file --origin_path="/etc/systemd/system/$app-celery.service"
ynh_restore_file --origin_path="/etc/systemd/system/$app-beat.service"
ynh_restore_file --origin_path="/etc/systemd/system/$app.socket"

systemctl enable "$app-celery" --quiet
systemctl enable "$app-beat" --quiet
systemctl enable "$app" --quiet
systemctl enable "$app.socket" --quiet
yunohost service add "$app" --description="Manage podcast subscriptions, and sync them between apps and devices" --log=systemd

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression --message="Reloading NGINX web server and $app's service..." --weight=1

ynh_systemd_action --service_name="$app.socket" --action="start" --log_path=systemd --line_match="Listening on"
ynh_systemd_action --service_name="$app" --action="start" --log_path=systemd --line_match="Started"
ynh_systemd_action --service_name="$app-celery" --action="start" --log_path=systemd --line_match="ready."
ynh_systemd_action --service_name="$app-beat" --action="start" --log_path=systemd --line_match="Starting..."

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
